
        <h2>Professores da escola</h2>
        <h2>Editar</h2>

        <form method="post">
        
<label>Nome</label><input type="text" name="nome" value="<?php echo $dados->campos['nome'];?>" /><br> 
<label>Email</label><input type="text" name="email" value="<?php echo $dados->campos['email'];?>" /><br> 
<label>Turma</label><input type="text" name="turma_id" value="<?php echo $dados->campos['turma_id'];?>" /><br>
<input type="submit">        
        
        
        </form>

</table>
