
        <h2>Professores da escola</h2>
        <a href="?controller=professor&method=insert">novo</a>
        <table>
        <?php
foreach ($dados as $professor):
	?>

	<tr>
		<td><?php echo $professor->campos['nome'];?></td>
		<td><?php echo $professor->campos['email'];?></td>
		<td><?php echo $professor->campos['turma_id'];?></td>
		<td>
			<a href="?controller=professor&method=edit&prof_id=<?php echo $professor->campos['prof_id'];?>">editar</a>
			<a href="?controller=professor&method=delete&prof_id=<?php echo $professor->campos['prof_id'];?>">excluir</a>
		</td>
	</tr>

	<?php
	
endforeach;
        ?>
</table>
