<html>
    <body>
        <form action="" method="post">
            <table border='1'>
                <tr>
                    <td>Buscar:</td>
                    <td colspan="3">
                        <input name="busca">
                        <input type="submit" value="Buscar">
                    </td>
                </tr>
                <tr>
                    <td colspan="4">
                        <a href="inserir.php">NOVO+</a>
                    </td>
                </tr>
                <tr>
                    <td>#</td>
                    <td>Nome</td>
                    <td>Email</td>
                    <td>Ações</td>
                </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <a href="alterar.php?controller=professor&method=alterar&id=">
                                Alterar
                            </a>
                        </td>
                        <td>
                            <a href="excluir.php?id=">
                                Excluir
                            </a>
                        </td>
                    </tr>
            </table>
        </form>
    </body>
</html>