

<footer>
<h4>MEU RODAPE</h4>
<nav class="navbar navbar-inverse navbar-fixed-bottom">
<ul>
<li><a href="/frame/public/?controller=professor">index</a></li>
<li><a href="/frame/public/?controller=professor">professor</a></li>
<li><a href="/frame/public/?controller=aluno">alunos</a></li>
<li><a href="/frame/public/?controller=turmas">turmas</a></li>
</ul>
</nav>
</footer>

</div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
</body>
</html>