<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<title>MVC da Escola</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

   <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/theme/theme.css" rel="stylesheet">
    <style>
    
li {list-style: none; float: left; padding: 5px;}    
    
    </style>
</head>
<body role="document">
<header>

<nav class="navbar navbar-inverse navbar-fixed-top">
<ul>
<li><a href="/frame/public/?controller=professor">index</a></li>
<li><a href="/frame/public/?controller=professor">professor</a></li>
<li><a href="/frame/public/?controller=aluno">alunos</a></li>
<li><a href="/frame/public/?controller=turmas">turmas</a></li>
</ul>
</nav>
<div class="container theme-showcase" role="main">
<h1>MVC FrameWaldo</h1>

