<html>
    <body>
        <form action="" method="post">
            <table border='1'>
                <tr>
                    <td>Buscar:</td>
                    <td colspan="3">
                        <input name="busca">
                        <input type="submit" value="Buscar">
                    </td>
                </tr>
                <tr>
                    <td colspan="4">
                        <a href="inserir.php">NOVO+</a>
                    </td>
                </tr>
                <tr>
                    <td>#</td>
                    <td>Nome</td>
                    <td>Email</td>
                    <td>Ações</td>
                </tr>
                <?php
                 
                foreach($dados['alunos'] as $aluno):
                ?>
                    <tr>
                        <td><?= $aluno->getAluno_id() ?></td>
                        <td><?= $aluno->getNome() ?></td>
                        <td><?= $aluno->getEmail() ?></td>
                        <td>
                            <a href="alterar.php?id=">
                                Alterar
                            </a>
                        </td>
                        <td>
                            <a href="excluir.php?id=">
                                Excluir
                            </a>
                        </td>
                    </tr>
                <?php
                    endforeach; 
                ?>
            </table>
        </form>
    </body>
</html>